line-length = 100

[lint]
select = ["ALL"]
unfixable = ["T201"]
ignore = [
    "D100",
    "D104",
    "D103",
    "D101",
    "ANN401",
    "E501",
    "TC002",
    "TC006",
    "D107",
    "D102",
    "TC001",
]

[lint.per-file-ignores]
"__init__.py" = [
    "F401",  # Module imported but unused
]
"**/migrations/**" = [
    "ANN201",  # Missing return type annotation for public function
    "ANN001",  # Missing type annotation for function argument
    "ARG001",  # Unused function argument"
    "RUF012",  # Mutable class attributes
]
"**/api.py" = [
    "ARG001",  # Unused function argument: `request`
]
"**/settings.py" = [
    "RUF012",  # Unused function argument: `request`
]
"tests/**" = [
    "S101",  # Use of assert detected
    "PT003",
]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[lint.pep8-naming]
classmethod-decorators = [
    "pydantic.validator",
    "pydantic.field_validator",
]

[lint.flake8-pytest-style]
fixture-parentheses = true
mark-parentheses = false

[lint.pydocstyle]
convention = "google"
